version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: micro-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=micro-service
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    networks:
      microservice_network:
        ipv4_address: 172.19.0.10

  pgadmin:
    image: dpage/pgadmin4
    container_name: micro-pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
    networks:
      microservice_network:
        ipv4_address: 172.19.0.11

  rabbitmq:
    image: rabbitmq:3.12.1-management
    container_name: micro-rabbitMQ
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=root
    networks:
      microservice_network:
        ipv4_address: 172.19.0.12
networks:
  microservice_network:
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16